# Generated by Django 4.2 on 2023-05-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de cita')),
                ('hora_cita', models.TimeField(help_text='HH/MM/SS', max_length=15, verbose_name='Hora de cita')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_mantenimiento', models.CharField(max_length=45, verbose_name='Historial de mantenimiento')),
                ('historial_reparaciones', models.CharField(max_length=45, verbose_name='Historial de reparaciones')),
            ],
            options={
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
