# Generated by Django 4.2.4 on 2023-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cita',
            name='contacto',
            field=models.CharField(default='ValorPredeterminado', max_length=10, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion_cita',
            field=models.CharField(default='ValorPredeterminado', max_length=50, verbose_name='Descripcion de la cita'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_mantenimiento',
            field=models.CharField(choices=[('Aplazado', 'Aplazado'), ('Iniciado', 'Iniciado'), ('Terminado', 'Terminado')], default='Iniciado', max_length=10, verbose_name='Estado Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Pospuesta', 'Pospuesta'), ('Cancelada', 'Cancelada'), ('En proceso', 'Enproceso'), ('Finalizada', 'Finalizada')], default='Programada', max_length=10, verbose_name='Estado'),
        ),
    ]
