# Generated by Django 4.2.4 on 2023-08-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_remove_cita_telefono_cita_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='estado',
            new_name='estado_cita',
        ),
        migrations.AlterField(
            model_name='cita',
            name='contacto',
            field=models.CharField(default='', max_length=10, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion_cita',
            field=models.CharField(default='', max_length=50, verbose_name='Descripcion de la cita'),
        ),
    ]
