# Generated by Django 4.2.4 on 2023-08-06 14:53

from django.db import migrations, models
import mantenimiento.models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_rename_estado_cita_estado_cita_alter_cita_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='descripcion_cita',
            field=models.CharField(default='', max_length=50, validators=[mantenimiento.models.alphabetic_validator], verbose_name='Descripcion de la cita'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='historial_mantenimiento',
            field=models.CharField(max_length=45, validators=[mantenimiento.models.alphabetic_validator], verbose_name='Historial de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='historial_reparaciones',
            field=models.CharField(max_length=45, validators=[mantenimiento.models.alphabetic_validator], verbose_name='Historial de reparaciones'),
        ),
    ]
