# Generated by Django 4.1.5 on 2023-08-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0026_alter_vehiculo_identificacion'),
        ('mantenimiento', '0005_delete_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='placa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo', verbose_name=' Nombre Usuario'),
        ),
    ]
