# Generated by Django 4.1.5 on 2023-08-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('mantenimiento', '0006_cita_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombreservicios',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.servicio', verbose_name='Nombre servicio'),
        ),
    ]
