# Generated by Django 4.1.7 on 2023-04-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=15, verbose_name='Factura')),
                ('servicio', models.CharField(max_length=25, verbose_name='Servicio')),
                ('cantidad', models.CharField(max_length=15, verbose_name='Cantidad')),
                ('precio_unitario', models.CharField(max_length=10, verbose_name='Precio Unitario')),
                ('precio_total', models.CharField(max_length=10, verbose_name='Precio Total')),
            ],
            options={
                'verbose_name_plural': 'Detalle Factura',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(help_text='DD/MM/AAAA', verbose_name='Fecha de Venta')),
                ('cliente', models.CharField(max_length=10, verbose_name='Cliente')),
                ('vehiculo', models.CharField(max_length=10, verbose_name='Vehiculo')),
                ('forma_pago', models.CharField(choices=[('D', 'Tarjeta de Debito'), ('C', 'Tarjeta de Credito'), ('E', 'Efectivo')], max_length=2, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name_plural': 'facturacion',
            },
        ),
        migrations.CreateModel(
            name='Venta_detalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.venta', verbose_name='Venta')),
                ('detalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.detallefactura', verbose_name='Detalle Factura')),
            ],
        ),
    ]
