# Generated by Django 4.1.7 on 2023-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Venta'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(max_length=25, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('D', 'Tarjeta de Debito'), ('C', 'Tarjeta de Credito'), ('E', 'Efectivo')], max_length=2, verbose_name='Tipo de Pago'),
        ),
        migrations.DeleteModel(
            name='Venta_detalleFactura',
        ),
    ]
