# Generated by Django 4.1.7 on 2023-05-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_meta_alter_venta_options_alter_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'verbose_name_plural': 'DetalleFactura'},
        ),
    ]
