# Generated by Django 4.1.7 on 2023-05-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_detallefactura_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meta',
        ),
    ]
