# Generated by Django 4.1.7 on 2023-05-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_detallefactura_estado_venta_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventass'},
        ),
    ]
