# Generated by Django 4.1.7 on 2023-05-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_venta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
    ]
