# Generated by Django 4.1.7 on 2023-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_venta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('Debito', 'Tarjeta de Debito'), ('Credito', 'Tarjeta de Credito'), ('Efectivo', 'Efectivo')], max_length=10, verbose_name='Tipo de Pago'),
        ),
    ]
