# Generated by Django 4.1.7 on 2023-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_detallefactura_estado_alter_venta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('D', 'Tarjeta de Debito'), ('C', 'Tarjeta de Credito'), ('E', 'Efectivo')], max_length=2, verbose_name='Tipo de Pago'),
        ),
    ]
