# Generated by Django 4.1.7 on 2023-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_detallefactura_estado_alter_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura',
            field=models.IntegerField(default=0, verbose_name='Factura'),
        ),
    ]
