# Generated by Django 4.1.7 on 2023-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_alter_venta_estado_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.IntegerField(unique=True, verbose_name='Factura'),
        ),
    ]
