# Generated by Django 4.1.7 on 2023-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_venta_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.IntegerField(default=0, verbose_name='Factura'),
        ),
    ]
