# Generated by Django 4.1.7 on 2023-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_remove_detallefactura_factura_remove_venta_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Venta'),
        ),
    ]
