# Generated by Django 4.1.7 on 2023-07-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_alter_detallefactura_venta_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.venta', verbose_name='Venta'),
        ),
    ]
