# Generated by Django 4.1.7 on 2023-07-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_remove_detallefactura_venta_detallefactura_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturacion.venta', verbose_name='Venta'),
        ),
    ]
