# Generated by Django 4.2.4 on 2023-08-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
    ]
