# Generated by Django 4.1.5 on 2023-10-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0034_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='vehiculo',
        ),
    ]
