# Generated by Django 4.1.5 on 2023-10-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_cita_nombreservicios'),
        ('facturacion', '0035_remove_venta_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_cita',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.cita', verbose_name=' Nombre Usuario'),
        ),
    ]
