# Generated by Django 4.1.5 on 2023-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_remove_venta_cliente_venta_fecha_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='identificacion',
        ),
    ]
