# Generated by Django 4.1.7 on 2023-05-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=25, verbose_name=' Linea ')),
                ('cilindraje', models.CharField(choices=[('0', '1.000 cc'), ('1', '1.400 cc'), ('2', '1.600 cc'), ('3', '2.000 cc')], default='0', max_length=3, verbose_name='Cilindraje')),
                ('transmision', models.CharField(choices=[('0', 'Manual'), ('1', 'Automatico')], default='0', max_length=1, verbose_name='Transmision')),
                ('capacidad', models.CharField(choices=[('0', 'Dos'), ('1', 'Tres'), ('2', 'Cinco'), ('3', 'Siete')], default='2', max_length=3, verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, verbose_name='Placa')),
                ('marca', models.CharField(max_length=25, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=25, verbose_name='Modelo')),
                ('tipo_aceite', models.CharField(max_length=25, verbose_name='Tipo de Aceite')),
                ('kilometraje', models.CharField(max_length=6, verbose_name='Kilometraje')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
