# Generated by Django 4.1.7 on 2023-05-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_linea_options_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'verbose_name_plural': 'Linea'},
        ),
    ]
