# Generated by Django 4.1.7 on 2023-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_linea_transmision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='capacidad',
            field=models.CharField(choices=[('Dos', 'Dos'), ('Tres', 'Tres'), ('Cinco', 'Cinco'), ('Siete', 'Siete')], max_length=10, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='cilindraje',
            field=models.CharField(choices=[('1.000 cc', '1.000 cc'), ('1.400 cc', '1.400 cc'), ('1.600 cc', '1.600 cc'), ('2.000 cc', '2.000 cc')], max_length=10, verbose_name='Cilindraje'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado'),
        ),
    ]
