# Generated by Django 4.1.7 on 2023-05-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_linea_capacidad_alter_linea_cilindraje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=10, verbose_name='Estado'),
        ),
    ]
