# Generated by Django 4.2.4 on 2023-08-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_vehiculo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario',
        ),
    ]
