# Generated by Django 4.1.5 on 2023-08-07 22:16

from django.db import migrations, models
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0011_remove_vehiculo_linea_remove_vehiculo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='capacidad',
        ),
        migrations.AlterField(
            model_name='linea',
            name='nombre_linea',
            field=models.CharField(default='', max_length=10, validators=[vehiculo.models.alphabetic_validator], verbose_name=' Linea '),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.CharField(default='', max_length=6, unique=True, validators=[vehiculo.models.numeric_validator], verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(default='', max_length=10, validators=[vehiculo.models.alphabetic_validator], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='', max_length=4, unique=True, validators=[vehiculo.models.numeric_validator], verbose_name='Modelo'),
        ),
    ]
