# Generated by Django 4.1.5 on 2023-08-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_arl_correo_arl_alter_arl_telefono_arl'),
        ('vehiculo', '0012_remove_linea_capacidad_alter_linea_nombre_linea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Cliente'),
        ),
    ]
