# Generated by Django 4.1.5 on 2023-08-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0015_vehiculo_nombre_linea_alter_vehiculo_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'verbose_name_plural': 'linea'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name_plural': 'vehiculo'},
        ),
    ]
