# Generated by Django 4.1.5 on 2023-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0017_alter_vehiculo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('RENAULT', 'RENAUT'), ('0', 'Inactivo'), ('1', 'Activo')], default='1', max_length=10, verbose_name='Estado'),
        ),
    ]
