# Generated by Django 4.1.5 on 2023-08-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_usuario_tipo_usuario'),
        ('vehiculo', '0019_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='identificacion',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'tipo_usuario': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name=' Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('RENAULT', 'Renault'), ('CHEVROLET', 'Chevrolet'), ('HONDA', 'Honda'), ('CITROEN', 'Citroën'), ('FORD', 'Ford'), ('HYUNDAI', 'Hyundai'), ('KIA', 'Kia'), ('MAZDA', 'Mazda'), ('MITSUBISHI', 'Mitsubishi'), ('NISSAN', 'Nissan')], max_length=10, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_aceite',
            field=models.CharField(max_length=6, verbose_name='Tipo de Aceite'),
        ),
    ]
