# Generated by Django 4.1.5 on 2023-08-10 21:51

from django.db import migrations, models
import django.db.models.deletion
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_usuario_tipo_usuario'),
        ('vehiculo', '0020_alter_vehiculo_identificacion_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='nombre_linea',
            field=models.CharField(default='', max_length=10, validators=[vehiculo.models.alphabetic_validator], verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='identificacion',
            field=models.ForeignKey(default=None, limit_choices_to={'tipo_usuario': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name=' Nombre Cliente'),
        ),
    ]
