# Generated by Django 4.1.5 on 2023-08-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0021_alter_linea_nombre_linea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='identificacion',
        ),
    ]
