# Generated by Django 4.1.5 on 2023-08-14 23:46

from django.db import migrations, models
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0022_remove_vehiculo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='nombre_linea',
            field=models.CharField(default='', max_length=20, validators=[vehiculo.models.alphabetic_validator], verbose_name='Linea'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_aceite',
            field=models.CharField(max_length=15, verbose_name='Tipo de Aceite'),
        ),
    ]
