# Generated by Django 4.1.5 on 2023-08-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0024_vehiculo_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='nombres',
            new_name='identificacion',
        ),
    ]
