# Generated by Django 4.1.5 on 2023-08-15 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usuario_confirmarcontraseña_and_more'),
        ('vehiculo', '0025_rename_nombres_vehiculo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='identificacion',
            field=models.ForeignKey(default=None, limit_choices_to={'tipo_usuario': 'Cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name=' Nombre Usuario'),
        ),
    ]
