# Generated by Django 4.1.7 on 2023-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0026_alter_vehiculo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_aceite',
            field=models.CharField(max_length=25, verbose_name='Tipo de Aceite'),
        ),
    ]
