# Generated by Django 4.1.5 on 2023-10-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0027_alter_vehiculo_tipo_aceite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='identificacion',
        ),
    ]
