# Generated by Django 4.2 on 2023-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcarepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombremarcarepuesto', models.CharField(max_length=45, verbose_name='Nombre')),
                ('disponibilidad', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='1', max_length=1, verbose_name='Disponibilidad')),
                ('gamaproductos', models.CharField(max_length=45, verbose_name='Gama productos')),
            ],
            options={
                'verbose_name_plural': 'marcarepuesto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproveedor', models.CharField(max_length=45, verbose_name='Nombre')),
                ('contactoproveedor', models.CharField(max_length=45, verbose_name='Contacto')),
                ('preciosproveedor', models.CharField(max_length=45, verbose_name='Precios')),
                ('plazoentrega', models.CharField(max_length=45, verbose_name='Plazo entrega')),
                ('historialpedidos', models.CharField(max_length=45, verbose_name='Historial pedidos')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerepuesto', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcionrepuesto', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('preciocomprarepuesto', models.CharField(max_length=45, verbose_name='Precio Compra Repuesto')),
                ('precioventarepuesto', models.CharField(max_length=45, verbose_name='Precio Venta Repuesto')),
                ('cantidadinventariorepuesto', models.CharField(max_length=45, verbose_name='Cantidad Inventario')),
                ('ubicacioninventario', models.CharField(max_length=45, verbose_name='Contacto')),
            ],
            options={
                'verbose_name_plural': 'repuestos',
            },
        ),
    ]
