# Generated by Django 4.2 on 2023-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='preciosproveedor',
        ),
        migrations.AlterField(
            model_name='marcarepuesto',
            name='disponibilidad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='plazoentrega',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha De Entrega'),
        ),
    ]
