# Generated by Django 4.2 on 2023-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_proveedor_preciosproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contactoproveedor',
            field=models.CharField(max_length=10, verbose_name='Contacto'),
        ),
    ]
