# Generated by Django 4.2.4 on 2023-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_proveedor_contactoproveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='marcarepuesto',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='marcarepuesto',
            name='gamaproductos',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='cantidadinventariorepuesto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='preciocomprarepuesto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precioventarepuesto',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='ubicacioninventario',
        ),
        migrations.AddField(
            model_name='marcarepuesto',
            name='gama_repuesto',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta')], default='Alta', max_length=4, verbose_name='Gama Repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costorepuesto',
            field=models.CharField(default='ValorPredeterminado', max_length=10, verbose_name='Costo Repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock',
            field=models.CharField(default='ValorPredeterminado', max_length=4, verbose_name='Cantidad Inventario'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='tipo_repuesto',
            field=models.CharField(choices=[('Insumo', 'Insumo'), ('Repuesto', 'Repuesto')], default='', max_length=8, verbose_name='Tipo De Repuesto'),
        ),
        migrations.AlterField(
            model_name='marcarepuesto',
            name='nombremarcarepuesto',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcionrepuesto',
            field=models.CharField(max_length=45, verbose_name='Descripcion Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombrerepuesto',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
