# Generated by Django 4.2.4 on 2023-08-06 00:08

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_delete_proveedor_remove_marcarepuesto_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='costorepuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcionrepuesto',
            field=models.CharField(blank=True, max_length=45, validators=[inventario.models.alphabetic_validator], verbose_name='Descripcion Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombrerepuesto',
            field=models.CharField(max_length=30, validators=[inventario.models.alphabetic_validator], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad Inventario'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='tipo_repuesto',
            field=models.CharField(choices=[('Insumo', 'Insumo'), ('Repuesto', 'Repuesto')], default='Repuesto', max_length=8, verbose_name='Tipo De Repuesto'),
        ),
    ]
