# Generated by Django 4.2.4 on 2023-08-06 02:36

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_repuesto_costorepuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcarepuesto',
            name='nombremarcarepuesto',
            field=models.CharField(max_length=25, validators=[inventario.models.alphabetic_validator], verbose_name='Nombre'),
        ),
    ]
