# Generated by Django 4.1.5 on 2023-08-07 22:16

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_repuesto_marcarepuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcarepuesto',
            name='nombremarcarepuesto',
            field=models.CharField(max_length=25, validators=[inventario.models.alphabetic_validator], verbose_name='Nombre Marca Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcionrepuesto',
            field=models.CharField(blank=True, max_length=85, validators=[inventario.models.alphabetic_validator], verbose_name='Descripcion Repuesto'),
        ),
    ]
