# Generated by Django 4.1.5 on 2023-08-07 23:14

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_marcarepuesto_nombremarcarepuesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuesto',
            options={'verbose_name_plural': 'repuesto'},
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombrerepuesto',
            field=models.CharField(max_length=30, validators=[inventario.models.alphabetic_validator], verbose_name='Nombre Repuesto'),
        ),
    ]
