# Generated by Django 4.1.5 on 2023-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_repuesto_options_alter_repuesto_nombrerepuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='costorepuesto',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Costo Repuesto'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='tipo_repuesto',
            field=models.CharField(choices=[('Insumo', 'Insumo'), ('Repuesto', 'Repuesto')], default='Repuesto', max_length=8, verbose_name='Repuesto'),
        ),
    ]
