# Generated by Django 4.2 on 2023-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_arl', models.CharField(max_length=15, verbose_name='Correo Arl')),
                ('telefono_arl', models.CharField(max_length=10, verbose_name='Telefono Arl')),
                ('correo_arl', models.CharField(max_length=50, verbose_name='Correo Arl')),
                ('fecha_inicioafi', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Inicio Afiliacion')),
                ('fecha_vencimientoafi', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha De Vencimiento Afiliacion')),
                ('estadoarl', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado Arl')),
            ],
            options={
                'verbose_name_plural': 'arls',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=45, verbose_name='Documento')),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('S', 'Secretaria'), ('M', 'Mecanico')], max_length=2, verbose_name='Rol')),
                ('rh', models.CharField(choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH')),
                ('primer_nombre', models.CharField(max_length=45, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=45, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, verbose_name='Segundo Apellido')),
                ('fecha_registro', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Registro')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('correo_personal', models.CharField(max_length=50, verbose_name='Correo Personal')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
