# Generated by Django 4.2 on 2023-04-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arl',
            options={'verbose_name_plural': 'arl'},
        ),
        migrations.RenameField(
            model_name='arl',
            old_name='estadoarl',
            new_name='estado',
        ),
    ]
