# Generated by Django 4.2 on 2023-06-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_arl_nombre_arl_alter_arl_telefono_arl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuarios'},
        ),
    ]
