# Generated by Django 4.2 on 2023-06-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arl',
            options={'verbose_name_plural': 'arls'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuario'},
        ),
    ]
