# Generated by Django 4.2.4 on 2023-08-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_arl_options_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arl',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='ValorPredeterminado', max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default='ValorPredeterminado', max_length=10, verbose_name='Identificacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='ValorPredeterminado', max_length=30, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería')], default='ValorPredeterminado', max_length=2, verbose_name='Tipo de identificacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'Administrador'), ('S', 'Secretaria'), ('M', 'Mecanico')], default='ValorPredeterminado', max_length=2, verbose_name='Tipo Usuario'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='correo_arl',
            field=models.CharField(max_length=30, verbose_name='Correo Arl'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='nombre_arl',
            field=models.CharField(max_length=20, verbose_name='Nombre Arl'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=10, verbose_name='Telefono Arl'),
        ),
    ]
