# Generated by Django 4.2.4 on 2023-08-05 20:30

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_arl_estado_remove_usuario_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='correo_arl',
            field=models.EmailField(max_length=30, verbose_name='Correo Arl'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='nombre_arl',
            field=models.CharField(max_length=20, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombre Arl'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=10, validators=[usuarios.models.numeric_validator], verbose_name='Telefono Arl'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rh',
            field=models.CharField(blank=True, choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('ABP', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Cédula Ciudadania', 'Cédula Ciudadania'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extrangería', 'Cédula de Extrangería')], default='Cédula Ciudadania', max_length=18, verbose_name='Tipo de identificacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecanico', 'Mecanico'), ('Cliente', 'Cliente')], default='', max_length=13, verbose_name='Tipo Usuario'),
        ),
    ]
