# Generated by Django 4.2.4 on 2023-08-06 14:53

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_arl_correo_arl_alter_arl_nombre_arl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='arl',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['Administrador', 'Mecanico', 'Secretaria']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.arl', verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='fecha_inicioafi',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Inicio Afiliación'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='fecha_vencimientoafi',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha De Vencimiento Afiliación'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=10, validators=[usuarios.models.numeric_validator], verbose_name='Teléfono Arl'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Cédula Ciudadanía', 'Cédula Ciudadanía'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extranjería', 'Cédula de Extranjería')], default='Cédula Ciudadanía', max_length=18, verbose_name='Tipo de identificación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecánico', 'Mecánico'), ('Cliente', 'Cliente')], default='', max_length=13, verbose_name='Tipo Usuario'),
        ),
    ]
