# Generated by Django 4.2.4 on 2023-08-07 02:43

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_arl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='fecha_inicioafi',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Inicio Afiliacion'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='fecha_vencimientoafi',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha De Vencimiento Afiliacion'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=10, validators=[usuarios.models.numeric_validator], verbose_name='Telefono Arl'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='arl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.arl', verbose_name='Arl'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('Cédula Ciudadania', 'Cédula Ciudadania'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extrangería', 'Cédula de Extrangería')], default='Cédula Ciudadania', max_length=18, verbose_name='Tipo de identificacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecanico', 'Mecanico'), ('Cliente', 'Cliente')], default='', max_length=13, verbose_name='Tipo Usuario'),
        ),
    ]
