# Generated by Django 4.2.4 on 2023-08-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_arl_fecha_inicioafi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuario'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='arl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.arl', verbose_name='ARL'),
        ),
    ]
