# Generated by Django 4.1.5 on 2023-08-07 22:16

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_options_alter_usuario_arl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='correo_arl',
            field=models.EmailField(max_length=40, verbose_name='Correo Arl'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=13, validators=[usuarios.models.numeric_validator], verbose_name='Telefono Arl'),
        ),
    ]
