# Generated by Django 4.1.5 on 2023-08-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_arl_correo_arl_alter_arl_telefono_arl'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirmarcontraseña',
            field=models.CharField(default='', max_length=20, verbose_name='Confirmar Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='', max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre De Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_personal',
            field=models.EmailField(default='', max_length=50, verbose_name='Correo Personal'),
        ),
    ]
