# Generated by Django 4.1.5 on 2023-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_cliente',
            field=models.BooleanField(default=False, verbose_name='Es Cliente'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
