# Generated by Django 4.1.5 on 2023-08-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_remove_usuario_es_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecanico', 'Mecanico'), ('Cliente', 'Cliente')], default='Cliente', max_length=13, verbose_name='Tipo Usuario'),
        ),
    ]
