# Generated by Django 4.1.5 on 2023-08-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_arl_correo_arl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='confirmarcontraseña',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Confirmar Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_personal',
            field=models.EmailField(blank=True, default='', max_length=50, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Nombre De Usuario'),
        ),
    ]
