# Generated by Django 4.1.5 on 2023-10-06 13:01

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_usuario_confirmarcontraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono2',
            field=models.CharField(default=1, max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Segundo Telefono'),
            preserve_default=False,
        ),
    ]
