# Generated by Django 4.1.5 on 2023-10-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_usuario_telefono2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rh',
            field=models.CharField(blank=True, choices=[('OP', 'O+'), ('ON', 'O-'), ('AP', 'A+'), ('AN', 'A-'), ('BP', 'B+'), ('BN', 'B-'), ('AB+', 'AB+'), ('ABN', 'AB-')], max_length=3, verbose_name='Factor RH'),
        ),
    ]
