# Generated by Django 4.1.5 on 2023-10-25 13:13

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_usuario_rh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='telefono_arl',
            field=models.CharField(max_length=10, validators=[usuarios.models.numeric_validator], verbose_name='Telefono Arl'),
        ),
    ]
