# Generated by Django 4.1.5 on 2023-10-26 02:31

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_arl_telefono_arl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='arl',
            name='fecha_inicioafi',
            field=models.DateField(verbose_name='Inicio De La Afiliación'),
        ),
        migrations.AlterField(
            model_name='arl',
            name='fecha_vencimientoafi',
            field=models.DateField(verbose_name='Vencimiento De La Afiliación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono2',
            field=models.CharField(blank=True, max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Segundo Telefono'),
        ),
    ]
