# Generated by Django 4.1.5 on 2023-10-29 13:12

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Nombres')),
                ('apellidos', models.CharField(default='', max_length=30, validators=[usuarios.models.alphabetic_validator], verbose_name='Apellidos')),
                ('tipo_identificacion', models.CharField(choices=[('Cédula Ciudadania', 'Cédula Ciudadania'), ('Tarjeta Identidad', 'Tarjeta de Identidad'), ('Cédula Extrangería', 'Cédula de Extrangería')], default='Cédula Ciudadania', max_length=18, verbose_name='Tipo de identificacion')),
                ('identificacion', models.CharField(default='', max_length=10, unique=True, validators=[usuarios.models.numeric_validator], verbose_name='Identificacion')),
                ('telefono', models.CharField(max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Telefono')),
                ('telefono2', models.CharField(blank=True, max_length=11, validators=[usuarios.models.numeric_validator], verbose_name='Segundo Telefono')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Secretaria', 'Secretaria'), ('Mecanico', 'Mecanico')], default='Mecanico', max_length=13, verbose_name='Tipo Usuario'),
        ),
    ]
