# Generated by Django 4.2 on 2023-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_servicio',
            options={'verbose_name_plural': 'Detalle_servicio'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': 'Servicio'},
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='fecha_servicio',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Servicio'),
        ),
    ]
