# Generated by Django 4.2 on 2023-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_detalle_servicio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_servicio',
            name='fecha_servicio',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Registro'),
        ),
    ]
