# Generated by Django 4.1.7 on 2023-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicio_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje',
            field=models.CharField(default=0, max_length=8, verbose_name='Kilometraje'),
        ),
    ]
