# Generated by Django 4.1.5 on 2023-08-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_marcarepuesto_nombremarcarepuesto_and_more'),
        ('servicio', '0003_alter_detalle_servicio_fecha_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_servicio',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuesto', verbose_name='Repuesto'),
        ),
    ]
