# Generated by Django 4.1.7 on 2023-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_detalle_servicio_costoservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_servicio',
            name='costoservicio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Costo Servico'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='descripcion',
            field=models.CharField(default='', max_length=45, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='nombreservicio',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Servicio'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='tipo_servicio',
            field=models.CharField(default='', max_length=45, verbose_name='Tipo de Servicio'),
        ),
    ]
