# Generated by Django 4.1.5 on 2023-08-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_repuesto_options_alter_repuesto_nombrerepuesto'),
        ('usuarios', '0013_alter_arl_correo_arl_alter_arl_telefono_arl'),
        ('servicio', '0005_rename_repuesto_detalle_servicio_nombrerepuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_servicio',
            name='nombres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Nombre Repuesto'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='nombrerepuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuesto', verbose_name='Nombre Repuesto'),
        ),
    ]
