# Generated by Django 4.1.7 on 2023-10-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0027_alter_vehiculo_tipo_aceite'),
        ('servicio', '0005_alter_detalle_servicio_costoservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='kilometraje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculo.vehiculo', verbose_name='Vehiculo'),
        ),
    ]
