# Generated by Django 4.1.7 on 2023-10-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_servicio_kilometraje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='kilometraje',
        ),
    ]
