# Generated by Django 4.1.5 on 2023-08-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_arl_correo_arl_alter_arl_telefono_arl'),
        ('servicio', '0006_detalle_servicio_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='tecnico',
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='nombres',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'Mecanico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Mecanico'),
        ),
    ]
