# Generated by Django 4.1.5 on 2023-08-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_repuesto_costorepuesto_and_more'),
        ('servicio', '0007_remove_detalle_servicio_tecnico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre',
            new_name='nombreservicio',
        ),
        migrations.AddField(
            model_name='detalle_servicio',
            name='nombreservicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.servicio', verbose_name='Costo Servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='costoservicio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Costo  Servico'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='nombrerepuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuesto', verbose_name='Costo Repuesto'),
        ),
    ]
