# Generated by Django 4.1.7 on 2023-10-06 16:14

from django.db import migrations, models
import servicio.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_remove_servicio_kilometraje'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='kilometraje',
            field=models.CharField(default=0, max_length=6, validators=[servicio.models.numeric_validator], verbose_name='Kilometraje'),
        ),
    ]
