# Generated by Django 4.1.5 on 2023-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_alter_servicio_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default='0:00:00', verbose_name='Duración de la cita'),
        ),
    ]
