# Generated by Django 4.1.5 on 2023-08-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_repuesto_costorepuesto_and_more'),
        ('usuarios', '0020_alter_usuario_confirmarcontraseña_and_more'),
        ('servicio', '0010_alter_servicio_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='estado_vehiculo',
        ),
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='fecha_servicio',
        ),
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='nombrerepuesto',
        ),
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='detalle_servicio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='costoservicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='detalle_servicio',
            name='costoservicio',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Costo  Servico'),
        ),
        migrations.AddField(
            model_name='detalle_servicio',
            name='descripcion',
            field=models.CharField(default='', max_length=45, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='detalle_servicio',
            name='duracion',
            field=models.DurationField(default='0:00:00', verbose_name='Duración de la cita'),
        ),
        migrations.AddField(
            model_name='detalle_servicio',
            name='tipo_servicio',
            field=models.CharField(default='', max_length=45, verbose_name='Tipo de Servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado_vehiculo',
            field=models.CharField(default='', max_length=45, verbose_name='Estado del vehiculo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_servicio',
            field=models.DateField(default='', help_text='MM/DD/AAAA', verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='kilometraje',
            field=models.IntegerField(default='', verbose_name='Kilometraje'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombrerepuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.repuesto', verbose_name='Costo Repuesto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombres',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'Mecanico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Mecanico'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observaciones',
            field=models.CharField(default='', max_length=45, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='nombreservicio',
            field=models.CharField(default='', max_length=20, verbose_name='Nombre de Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreservicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.detalle_servicio', verbose_name='Costo Servicio'),
        ),
    ]
