# Generated by Django 4.1.5 on 2023-08-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0012_remove_detalle_servicio_costoservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_servicio',
            name='fecha_servicio',
            field=models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Registro'),
        ),
    ]
