# Generated by Django 4.1.5 on 2023-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0013_alter_detalle_servicio_fecha_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_servicio',
            name='estado_vehiculo',
            field=models.CharField(max_length=45, verbose_name='Estado del vehiculo'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='kilometraje',
            field=models.IntegerField(verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='detalle_servicio',
            name='observaciones',
            field=models.CharField(max_length=45, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(max_length=45, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreservicio',
            field=models.CharField(max_length=20, verbose_name='Nombre de Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(max_length=45, verbose_name='Tipo de Servicio'),
        ),
    ]
