# Generated by Django 4.1.5 on 2023-08-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0015_remove_detalle_servicio_estado_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_servicio',
            field=models.DateField(default='', help_text='MM/DD/AAAA', verbose_name='Fecha de Registro'),
        ),
    ]
